title: ZANDCLASS
description: AI賦能 邁向卓越 直至超越
theme: jekyll-theme-minimal

# 作者資訊
author:
  name: Zachary Wu
  title: 藍海培訓顧問有限公司 負責人
  bio: 曾任職出版業十餘年，具產品、業務、銷售、倉儲、管理 多元職務經歷
  education: 輔仁大學法律學院畢業
  skills: AI培訓 / 知識數位化 / 自媒體 / 攝影 / 平面設計 / 出版製作
  book: 著作《智能轉型 AI在商業世界的實踐指南》

# 導航設定
navigation:
  - title: AI應用思維
    children:
      - title: AI應用框架
        url: /guide/ai-framework
      - title: 商業框架
        url: /guide/business-framework
  - title: AI應用實踐
    children:
      - title: 文字生成類
        url: /ai-tools/text-generation
      - title: 圖片生成類
        url: /ai-tools/image-generation
      - title: 聲音生成類
        url: /ai-tools/audio-generation
      - title: 影片生成類
        url: /ai-tools/video-generation

# GitHub 設定
github:
  is_project_page: true
  repository_url: https://github.com/ZACK-TW/ZANDCLASS
  
# 社交媒體連結
social:
  linktree: # 您的 Linktree 連結