# 網站基本信息
title: ZANDCLASS
tagline: AI賦能 邁向卓越 直至超越
description: 這是一個從現實生活出發的AI落地應用資訊站，提供獨到的思維導航和實操的成果展示。

# 作者信息
author:
  name: Zachary Wu
  title: 藍海培訓顧問有限公司 負責人
  works: 著作《智能轉型 AI在商業世界的實踐指南》

# GitHub 設定
repository: ZACK-TW/ZANDCLASS
url: https://zack-tw.github.io
baseurl: /ZANDCLASS

# 主選單設定
menu_groups:
  - name: AI應用思維
    link: /ai-thinking
    items:
      - name: AI應用框架
        link: /ai-thinking/framework
      - name: 商業框架
        link: /ai-thinking/business

  - name: AI應用實踐
    link: /ai-practice
    items:
      - name: 文字生成類
        link: /ai-practice/text
        description: 探索文字生成的應用
      - name: 圖片生成類
        link: /ai-practice/image
        description: 了解圖像生成的可能性
      - name: 聲音生成類
        link: /ai-practice/audio
        description: 發掘語音應用的潛力
      - name: 影片生成類
        link: /ai-practice/video
        description: 探索影片製作的新方向

# 建置設定
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# 網站特色
features:
  - 從實際需求出發
  - 提供完整的思維框架
  - 分享具體的應用案例
  - 持續更新最新資訊

# 語言設定
lang: zh-TW