title: ZANDCLASS
description: 這是一個從現實生活出發的AI落地應用資訊站，提供獨到的思維導航和實操的成果展示。
slogan: AI賦能 邁向卓越 直至超越

# 導航設定
navigation:
  - section: AI應用思維
    items:
      - title: AI應用框架
        url: /guide/ai-framework
        description: 了解AI應用的核心原理與架構
      - title: 商業框架
        url: /guide/business-framework
        description: 探索AI在商業中的實踐方法
  - section: AI應用實踐
    items:
      - title: 文字生成類
        url: /ai-tools/text-generation
        description: 探索文字生成的應用
      - title: 圖片生成類
        url: /ai-tools/image-generation
        description: 了解圖像生成的可能性
      - title: 聲音生成類
        url: /ai-tools/audio-generation
        description: 發掘語音應用的潛力
      - title: 影片生成類
        url: /ai-tools/video-generation
        description: 探索影片製作的新方向

# 作者信息
author:
  name: Zachary Wu
  title: 藍海培訓顧問有限公司 負責人
  book: 著作《智能轉型 AI在商業世界的實踐指南》

# Jekyll 設定
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink: /:categories/:title/

# GitHub Pages 設定
baseurl: "/ZANDCLASS"
url: "https://zack-tw.github.io"

# 建置排除
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md