name: docs

on:
  # 推送到主分支時觸發
  push:
    branches: [ main ]
  # 手動觸發
  workflow_dispatch:

# 設定 GITHUB_TOKEN 的權限
permissions:
  contents: read
  pages: write
  id-token: write

# 允許一個並發部署
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # 建構工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 不限制 git fetch 的深度
      
      # 設定 Node.js 環境
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      
      # 設定 Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # 安裝依賴
      - name: Install dependencies
        run: npm ci
      
      # 建構專案
      - name: Build with VuePress
        run: |
          npm run docs:build
          touch docs/.vuepress/dist/.nojekyll
      
      # 上傳成品
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/.vuepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2